### ISSUE TITLE
repository setup tracking issue

### ISSUE THREAD

**Issue by llhuii** [kubeedge/sedna#2]
This issue is to track the things need to be done for completely setup our repository.
- [ ] add fossa checker for licenses checking
- [x] add prowbot support for auto merging pr etc.
- [x] add e2e testcases, current empty

**Comment by llhuii** [comment]
progress:
finish to add prowbot support by adding kubeedge-bot to this project.

**Comment by llhuii** [comment]
for the issue: 
> update the container image repo of [installation doc](/docs/setup/install.md)
