### ISSUE TITLE
Contributor Experience Improvement Tracking Issue

### ISSUE THREAD

**Issue by llhuii** [kubeedge/sedna#3]
One of the top priority work to do duing the next few months is to improve contributor experience, help more new contributors get on board.

This issue is to track the things need to be done.

### General
* [ ]  [Docs] Separate user manual and contributor guide docs, TBD.
* [ ]  [Docs] Governance doc, general introduction of how the community is operated, including SIG/WG setup etc.
* [ ]  [Docs] Membership guid
* [ ]  [Docs] Code of Conduct

### Releases
* [ ]  [Docs] Release lifecycle
* [ ]  [Tooling] Release automation: automate the process of making a new release.
* [ ]  [Docs] Usage of Milestone and Projects view.

### Feature guide
* [ ]  [Docs] Feature lifecycle
* [ ]  [Docs] Proposing Enhancements (features), TBD.
* [ ]  [Docs] How to write Enhancement (KEP) guide, TBD.

### Developer self-service
* [ ]  [Docs] local env setup (for development), with [local-up script already done](/hack/local-up.sh)
* [ ]  [Docs] PR flow, TBD.
* [ ]  [Docs] Debugging guide, TBD.
* [ ]  [Docs] Reporting Bugs
* [ ]  [Tooling] Speed up CI checking.
* [ ]  [Tooling] enable more prow functions, e.g. `retest`, TBD.
* [ ]  [Tooling] Enable document preview on pull requests

**Comment by llhuii** [comment]
mark the reference https://github.com/kubeedge/kubeedge/issues/944 here
