### ISSUE TITLE
tracking issues of pod template support #19

### ISSUE THREAD

**Issue by llhuii** [kubeedge/sedna#31]
- [x] refactor workerSpec of API/implementation into pod template
- [x] change CRD of all features, and we can avoid this by kube-builder #11
- [x] update the installation doc
- [x] update the local-up script
- [x] update the proposal
- [ ] update all three examples
- [x] add all example dockerfiles

**Comment by llhuii** [comment]
cleanups: 
- [ ] remove imageHub in gm-config
- [ ] remove `build/worker`

**Comment by llhuii** [comment]
- [ ] update incremental learning example doc
- [ ] update joint inference example doc
- [ ] update federated learning example doc
