### ISSUE TITLE
feature enhancements tracking issue

### ISSUE THREAD

**Issue by llhuii** [kubeedge/sedna#4]
This issue is to track these known enhancements:
- [ ] add pod template like support for worker spec
- [ ] add dataset management with central storage support
- [ ] add model management with central storage support
- [ ] add worker script directory with central storage support
- [ ] add example code style checker
- [ ] add descriptions for CRD fields

**Comment by jaypume** [comment]
[SPACE] make the python lib interface more clearer
[SPACE] model serving should support hot loading & multiple models
[SPACE] manually copying training script to edge node is not recommended
[SPACE] the basic TensorFlow images in the examples needs to be unified to one version
[SPACE] the networking differences need to be considered when the LC is deployed on the cloud

**Comment by llhuii** [comment]
> * [ ]   make the python lib interface more clearer
> * [ ]  model serving should support hot loading & multiple models
> * [ ]  manually copying training script to edge node is not recommended
> * [ ]  the basic TensorFlow images in the examples needs to be unified to one version
> * [ ]  the networking differences need to be considered when the LC is deployed on the cloud

Added

**Comment by kevin-wangzefeng** [comment]
To follow up for the feature enhancements, it's recommanded to create separated tracking issues for each items.
